version: '3'
services:
  node-appbackup:
    build: .
    ports:
      - "3000:3000"
      # -"8080:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # env_file:
    #   - ./.env